--
-- PostgreSQL database dump
--

\restrict Hakz1sMksaZAG2aNuHCtcxOIVl7eIWLMfNMH5l3Q7ZgKhcSEvUREOEdeRKhrysP

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: about; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.about (
    id integer NOT NULL,
    version text NOT NULL,
    build_time timestamp with time zone NOT NULL,
    commit_hash text,
    commit_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.about OWNER TO postgres;

--
-- Name: about_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.about_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.about_id_seq OWNER TO postgres;

--
-- Name: about_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.about_id_seq OWNED BY public.about.id;


--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id integer NOT NULL,
    username character varying(255),
    password character varying(255),
    department character varying(255),
    islocker boolean
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_log (
    id bigint NOT NULL,
    source text NOT NULL,
    level text NOT NULL,
    text text NOT NULL,
    args jsonb,
    context jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.app_log OWNER TO postgres;

--
-- Name: app_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.app_log_id_seq OWNER TO postgres;

--
-- Name: app_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_log_id_seq OWNED BY public.app_log.id;


--
-- Name: chat_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_log (
    id bigint NOT NULL,
    session_id text NOT NULL,
    username text,
    role text NOT NULL,
    content text NOT NULL,
    llm_model text,
    rag_used boolean DEFAULT false,
    rag_sources jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    parts jsonb,
    metadata jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.chat_log OWNER TO postgres;

--
-- Name: chat_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.chat_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.chat_log_id_seq OWNER TO postgres;

--
-- Name: chat_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.chat_log_id_seq OWNED BY public.chat_log.id;


--
-- Name: chat_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_session (
    id text NOT NULL,
    username text,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    message_count integer DEFAULT 0,
    llm_model text,
    metadata jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.chat_session OWNER TO postgres;

--
-- Name: conversation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversation (
    id bigint NOT NULL,
    username character varying(64) NOT NULL,
    title character varying(255) DEFAULT '新对话'::character varying NOT NULL,
    model character varying(64),
    system_prompt character varying(128),
    message_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL
);


ALTER TABLE public.conversation OWNER TO postgres;

--
-- Name: conversation_backup_20260922; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversation_backup_20260922 (
    id bigint,
    username character varying(64),
    title character varying(255),
    model character varying(64),
    system_prompt character varying(128),
    message_count integer,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    archived boolean,
    metadata jsonb
);


ALTER TABLE public.conversation_backup_20260922 OWNER TO postgres;

--
-- Name: conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.conversation_id_seq OWNER TO postgres;

--
-- Name: conversation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.conversation_id_seq OWNED BY public.conversation.id;


--
-- Name: departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departments (
    id integer NOT NULL,
    code text NOT NULL,
    name text NOT NULL,
    short_name text,
    parent_id integer,
    manager text,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.departments OWNER TO postgres;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.departments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.departments_id_seq OWNER TO postgres;

--
-- Name: departments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.departments_id_seq OWNED BY public.departments.id;


--
-- Name: document_chunks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document_chunks (
    id integer NOT NULL,
    document_id integer,
    department text,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    embedding public.vector(1024),
    token_count integer,
    metadata jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.document_chunks OWNER TO postgres;

--
-- Name: document_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.document_chunks_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.document_chunks_id_seq OWNER TO postgres;

--
-- Name: document_chunks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.document_chunks_id_seq OWNED BY public.document_chunks.id;


--
-- Name: document_departments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.document_departments (
    document_id integer NOT NULL,
    department_id integer NOT NULL
);


ALTER TABLE public.document_departments OWNER TO postgres;

--
-- Name: documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    content text NOT NULL,
    embedding public.vector(1536)
);


ALTER TABLE public.documents OWNER TO postgres;

--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.documents_id_seq OWNER TO postgres;

--
-- Name: documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.documents_id_seq OWNED BY public.documents.id;


--
-- Name: llm; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.llm (
    id integer NOT NULL,
    llm_name character varying(255),
    llm_apikey character varying(512),
    llm_baseurl character varying(512),
    llm_model character varying(255),
    username character varying(255),
    is_default boolean DEFAULT false NOT NULL
);


ALTER TABLE public.llm OWNER TO postgres;

--
-- Name: llm_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.llm ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.llm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mcp_server; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mcp_server (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    description text,
    connection_type character varying(16) NOT NULL,
    connection_api jsonb DEFAULT '{}'::jsonb NOT NULL,
    auth_type character varying(16) DEFAULT 'none'::character varying NOT NULL,
    auth_config jsonb,
    status character varying(16) DEFAULT 'unknown'::character varying NOT NULL,
    last_error text,
    permission character varying(16) DEFAULT 'read'::character varying NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    tools jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_mcp_auth_type CHECK (((auth_type)::text = ANY ((ARRAY['none'::character varying, 'basic'::character varying, 'bearer'::character varying, 'api_key'::character varying])::text[]))),
    CONSTRAINT chk_mcp_connection_is_object CHECK ((jsonb_typeof(connection_api) = 'object'::text)),
    CONSTRAINT chk_mcp_connection_required_fields CHECK (((((connection_type)::text = ANY ((ARRAY['http'::character varying, 'sse'::character varying, 'ws'::character varying])::text[])) AND (connection_api ? 'url'::text)) OR (((connection_type)::text = ANY ((ARRAY['tcp'::character varying, 'grpc'::character varying])::text[])) AND (connection_api ? 'host'::text) AND (connection_api ? 'port'::text)) OR (((connection_type)::text = ANY ((ARRAY['ftp'::character varying, 'sftp'::character varying])::text[])) AND (connection_api ? 'host'::text)) OR (((connection_type)::text = 'stdio'::text) AND (connection_api ? 'command'::text)))),
    CONSTRAINT chk_mcp_connection_type CHECK (((connection_type)::text = ANY ((ARRAY['http'::character varying, 'sse'::character varying, 'stdio'::character varying, 'tcp'::character varying, 'ftp'::character varying, 'sftp'::character varying, 'ws'::character varying, 'grpc'::character varying])::text[]))),
    CONSTRAINT chk_mcp_name_format CHECK (((name)::text ~ '^[a-z][a-z0-9_-]{1,63}$'::text)),
    CONSTRAINT chk_mcp_permission CHECK (((permission)::text = ANY ((ARRAY['read'::character varying, 'write'::character varying, 'admin'::character varying])::text[]))),
    CONSTRAINT chk_mcp_status CHECK (((status)::text = ANY ((ARRAY['unknown'::character varying, 'connected'::character varying, 'error'::character varying, 'disabled'::character varying])::text[]))),
    CONSTRAINT chk_mcp_tools_is_array CHECK ((jsonb_typeof(tools) = 'array'::text))
);


ALTER TABLE public.mcp_server OWNER TO postgres;

--
-- Name: mcp_server_access; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mcp_server_access (
    id bigint NOT NULL,
    mcp_server_id bigint NOT NULL,
    username character varying(64) NOT NULL,
    permission character varying(16) DEFAULT 'read'::character varying NOT NULL,
    granted_by character varying(64),
    granted_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    revoked boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_access_permission CHECK (((permission)::text = ANY ((ARRAY['read'::character varying, 'write'::character varying, 'admin'::character varying])::text[])))
);


ALTER TABLE public.mcp_server_access OWNER TO postgres;

--
-- Name: mcp_server_access_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.mcp_server_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mcp_server_access_id_seq OWNER TO postgres;

--
-- Name: mcp_server_access_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.mcp_server_access_id_seq OWNED BY public.mcp_server_access.id;


--
-- Name: mcp_server_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.mcp_server_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.mcp_server_id_seq OWNER TO postgres;

--
-- Name: mcp_server_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.mcp_server_id_seq OWNED BY public.mcp_server.id;


--
-- Name: message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message (
    id bigint NOT NULL,
    conversation_id bigint NOT NULL,
    username character varying(64) NOT NULL,
    role character varying(16) NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    parts jsonb DEFAULT '[]'::jsonb NOT NULL,
    model character varying(64),
    prompt_tokens integer DEFAULT 0,
    completion_tokens integer DEFAULT 0,
    total_tokens integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT chk_message_role CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying, 'tool'::character varying])::text[])))
);


ALTER TABLE public.message OWNER TO postgres;

--
-- Name: message_backup_20260922; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.message_backup_20260922 (
    id bigint,
    conversation_id bigint,
    username character varying(64),
    role character varying(16),
    content text,
    parts jsonb,
    model character varying(64),
    prompt_tokens integer,
    completion_tokens integer,
    total_tokens integer,
    created_at timestamp with time zone,
    metadata jsonb
);


ALTER TABLE public.message_backup_20260922 OWNER TO postgres;

--
-- Name: message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.message_id_seq OWNER TO postgres;

--
-- Name: message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.message_id_seq OWNED BY public.message.id;


--
-- Name: skill; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.skill (
    id integer NOT NULL,
    name character varying(64) NOT NULL,
    display_name character varying(128),
    description text NOT NULL,
    input_schema jsonb NOT NULL,
    output_schema jsonb,
    handler_type character varying(32) NOT NULL,
    endpoint character varying(512),
    handler_ref character varying(255),
    auth_type character varying(32),
    auth_config jsonb,
    metadata jsonb,
    enabled boolean DEFAULT true NOT NULL,
    is_default boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.skill OWNER TO postgres;

--
-- Name: skill_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.skill_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.skill_id_seq OWNER TO postgres;

--
-- Name: skill_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.skill_id_seq OWNED BY public.skill.id;


--
-- Name: source_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.source_documents (
    id integer NOT NULL,
    title text NOT NULL,
    doc_type text,
    source_url text,
    ingested_at timestamp with time zone DEFAULT now(),
    metadata jsonb DEFAULT '{}'::jsonb
);


ALTER TABLE public.source_documents OWNER TO postgres;

--
-- Name: source_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.source_documents_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.source_documents_id_seq OWNER TO postgres;

--
-- Name: source_documents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.source_documents_id_seq OWNED BY public.source_documents.id;


--
-- Name: system_prompt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_prompt (
    id integer NOT NULL,
    system_prompt_name character varying(255),
    system_prompt_content character varying(204800),
    system_prompt_format character varying(20480),
    is_default boolean DEFAULT false NOT NULL
);


ALTER TABLE public.system_prompt OWNER TO postgres;

--
-- Name: system_prompt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_prompt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_prompt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token (
    id bigint NOT NULL,
    update_date date DEFAULT now(),
    username character varying(255),
    llm_model character varying(255),
    total_tokens bigint,
    prompt_tokens bigint,
    completion_tokens bigint
);


ALTER TABLE public.token OWNER TO postgres;

--
-- Name: token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: about id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.about ALTER COLUMN id SET DEFAULT nextval('public.about_id_seq'::regclass);


--
-- Name: app_log id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_log ALTER COLUMN id SET DEFAULT nextval('public.app_log_id_seq'::regclass);


--
-- Name: chat_log id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_log ALTER COLUMN id SET DEFAULT nextval('public.chat_log_id_seq'::regclass);


--
-- Name: conversation id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversation ALTER COLUMN id SET DEFAULT nextval('public.conversation_id_seq'::regclass);


--
-- Name: departments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments ALTER COLUMN id SET DEFAULT nextval('public.departments_id_seq'::regclass);


--
-- Name: document_chunks id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_chunks ALTER COLUMN id SET DEFAULT nextval('public.document_chunks_id_seq'::regclass);


--
-- Name: documents id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documents ALTER COLUMN id SET DEFAULT nextval('public.documents_id_seq'::regclass);


--
-- Name: mcp_server id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server ALTER COLUMN id SET DEFAULT nextval('public.mcp_server_id_seq'::regclass);


--
-- Name: mcp_server_access id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server_access ALTER COLUMN id SET DEFAULT nextval('public.mcp_server_access_id_seq'::regclass);


--
-- Name: message id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message ALTER COLUMN id SET DEFAULT nextval('public.message_id_seq'::regclass);


--
-- Name: skill id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill ALTER COLUMN id SET DEFAULT nextval('public.skill_id_seq'::regclass);


--
-- Name: source_documents id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.source_documents ALTER COLUMN id SET DEFAULT nextval('public.source_documents_id_seq'::regclass);


--
-- Name: about about_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.about
    ADD CONSTRAINT about_pkey PRIMARY KEY (id);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: account account_username_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_username_unique UNIQUE (username);


--
-- Name: app_log app_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_log
    ADD CONSTRAINT app_log_pkey PRIMARY KEY (id);


--
-- Name: chat_log chat_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_log
    ADD CONSTRAINT chat_log_pkey PRIMARY KEY (id);


--
-- Name: chat_session chat_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_pkey PRIMARY KEY (id);


--
-- Name: conversation conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversation
    ADD CONSTRAINT conversation_pkey PRIMARY KEY (id);


--
-- Name: departments departments_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_code_key UNIQUE (code);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: document_chunks document_chunks_document_id_chunk_index_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_document_id_chunk_index_key UNIQUE (document_id, chunk_index);


--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);


--
-- Name: document_departments document_departments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_departments
    ADD CONSTRAINT document_departments_pkey PRIMARY KEY (document_id, department_id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: llm llm_llm_model_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.llm
    ADD CONSTRAINT llm_llm_model_unique UNIQUE (llm_model);


--
-- Name: llm llm_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.llm
    ADD CONSTRAINT llm_pkey PRIMARY KEY (id);


--
-- Name: mcp_server_access mcp_server_access_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server_access
    ADD CONSTRAINT mcp_server_access_pkey PRIMARY KEY (id);


--
-- Name: mcp_server mcp_server_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server
    ADD CONSTRAINT mcp_server_pkey PRIMARY KEY (id);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);


--
-- Name: skill skill_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill
    ADD CONSTRAINT skill_name_key UNIQUE (name);


--
-- Name: skill skill_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.skill
    ADD CONSTRAINT skill_pkey PRIMARY KEY (id);


--
-- Name: source_documents source_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.source_documents
    ADD CONSTRAINT source_documents_pkey PRIMARY KEY (id);


--
-- Name: system_prompt system_prompt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.system_prompt
    ADD CONSTRAINT system_prompt_pkey PRIMARY KEY (id);


--
-- Name: token token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_pkey PRIMARY KEY (id);


--
-- Name: mcp_server_access uniq_access_user_server; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server_access
    ADD CONSTRAINT uniq_access_user_server UNIQUE (mcp_server_id, username);


--
-- Name: idx_about_version; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_about_version ON public.about USING btree (version);


--
-- Name: idx_access_server; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_access_server ON public.mcp_server_access USING btree (mcp_server_id) WHERE (revoked = false);


--
-- Name: idx_access_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_access_user ON public.mcp_server_access USING btree (username) WHERE (revoked = false);


--
-- Name: idx_app_log_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_log_level ON public.app_log USING btree (level, created_at DESC);


--
-- Name: idx_app_log_source; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_log_source ON public.app_log USING btree (source, created_at DESC);


--
-- Name: idx_app_log_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_log_time ON public.app_log USING btree (created_at DESC);


--
-- Name: idx_chat_log_session; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_log_session ON public.chat_log USING btree (session_id, created_at);


--
-- Name: idx_chat_log_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_log_time ON public.chat_log USING btree (created_at DESC);


--
-- Name: idx_chat_log_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_log_user ON public.chat_log USING btree (username, created_at DESC);


--
-- Name: idx_chat_session_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_session_user ON public.chat_session USING btree (username, started_at DESC);


--
-- Name: idx_chunks_doc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chunks_doc ON public.document_chunks USING btree (document_id);


--
-- Name: idx_departments_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_departments_active ON public.departments USING btree (is_active);


--
-- Name: idx_departments_parent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_departments_parent ON public.departments USING btree (parent_id);


--
-- Name: idx_doc_dept_dept; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_doc_dept_dept ON public.document_departments USING btree (department_id);


--
-- Name: idx_llm_default; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_llm_default ON public.llm USING btree (is_default) WHERE (is_default = true);


--
-- Name: idx_skill_default; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_skill_default ON public.skill USING btree (is_default) WHERE (is_default = true);


--
-- Name: idx_system_prompt_default; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_system_prompt_default ON public.system_prompt USING btree (is_default) WHERE (is_default = true);


--
-- Name: uniq_about_singleton; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_about_singleton ON public.about USING btree ((true));


--
-- Name: uniq_mcp_server_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_mcp_server_name ON public.mcp_server USING btree (name);


--
-- Name: departments departments_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: document_chunks document_chunks_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.source_documents(id) ON DELETE CASCADE;


--
-- Name: document_departments document_departments_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_departments
    ADD CONSTRAINT document_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- Name: document_departments document_departments_document_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.document_departments
    ADD CONSTRAINT document_departments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.source_documents(id) ON DELETE CASCADE;


--
-- Name: llm llm_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.llm
    ADD CONSTRAINT llm_username_fkey FOREIGN KEY (username) REFERENCES public.account(username);


--
-- Name: mcp_server_access mcp_server_access_mcp_server_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mcp_server_access
    ADD CONSTRAINT mcp_server_access_mcp_server_id_fkey FOREIGN KEY (mcp_server_id) REFERENCES public.mcp_server(id) ON DELETE CASCADE;


--
-- Name: message message_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversation(id) ON DELETE CASCADE;


--
-- Name: token token_llm_model_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_llm_model_fkey FOREIGN KEY (llm_model) REFERENCES public.llm(llm_model);


--
-- Name: token token_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_username_fkey FOREIGN KEY (username) REFERENCES public.account(username);


--
-- PostgreSQL database dump complete
--

\unrestrict Hakz1sMksaZAG2aNuHCtcxOIVl7eIWLMfNMH5l3Q7ZgKhcSEvUREOEdeRKhrysP

