/*
 Navicat Premium Dump SQL

 Source Server         : 104.168.125.34PostgreSql
 Source Server Type    : PostgreSQL
 Source Server Version : 160015 (160015)
 Source Host           : 104.168.125.34:5432
 Source Catalog        : iagent
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160015 (160015)
 File Encoding         : 65001

 Date: 23/09/2026 13:46:45
*/


-- ----------------------------
-- Table structure for llm
-- ----------------------------
DROP TABLE IF EXISTS "public"."llm";
CREATE TABLE "public"."llm" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "llm_name" varchar(255) COLLATE "pg_catalog"."default",
  "llm_apikey" varchar(512) COLLATE "pg_catalog"."default",
  "llm_baseurl" varchar(512) COLLATE "pg_catalog"."default",
  "llm_model" varchar(255) COLLATE "pg_catalog"."default",
  "username" varchar(255) COLLATE "pg_catalog"."default",
  "is_default" bool
)
;

-- ----------------------------
-- Uniques structure for table llm
-- ----------------------------
ALTER TABLE "public"."llm" ADD CONSTRAINT "llm_llm_model_unique" UNIQUE ("llm_model");

-- ----------------------------
-- Primary Key structure for table llm
-- ----------------------------
ALTER TABLE "public"."llm" ADD CONSTRAINT "llm_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table llm
-- ----------------------------
ALTER TABLE "public"."llm" ADD CONSTRAINT "llm_username_fkey" FOREIGN KEY ("username") REFERENCES "public"."account" ("username") ON DELETE NO ACTION ON UPDATE NO ACTION;
