/*
 Navicat Premium Dump SQL

 Source Server         : 104.168.125.34PostgreSql
 Source Server Type    : PostgreSQL
 Source Server Version : 160015 (160015)
 Source Host           : 104.168.125.34:5432
 Source Catalog        : iagent
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160015 (160015)
 File Encoding         : 65001

 Date: 23/09/2026 13:45:23
*/


-- ----------------------------
-- Table structure for system_prompt
-- ----------------------------
DROP TABLE IF EXISTS "public"."system_prompt";
CREATE TABLE "public"."system_prompt" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "system_prompt_name" varchar(255) COLLATE "pg_catalog"."default",
  "system_prompt_content" varchar(204800) COLLATE "pg_catalog"."default",
  "system_prompt_format" varchar(20480) COLLATE "pg_catalog"."default",
  "is_default" bool
)
;

-- ----------------------------
-- Primary Key structure for table system_prompt
-- ----------------------------
ALTER TABLE "public"."system_prompt" ADD CONSTRAINT "system_prompt_pkey" PRIMARY KEY ("id");
