/*
 Navicat Premium Dump SQL

 Source Server         : 104.168.125.34PostgreSql
 Source Server Type    : PostgreSQL
 Source Server Version : 160015 (160015)
 Source Host           : 104.168.125.34:5432
 Source Catalog        : iagent
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160015 (160015)
 File Encoding         : 65001

 Date: 13/09/2026 15:57:08
*/


-- ----------------------------
-- Table structure for token
-- ----------------------------
DROP TABLE IF EXISTS "public"."token";
CREATE TABLE "public"."token" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "date" date,
  "username" varchar(255) COLLATE "pg_catalog"."default",
  "llm_model" varchar(255) COLLATE "pg_catalog"."default",
  "tokenusage" int8
)
;

-- ----------------------------
-- Primary Key structure for table token
-- ----------------------------
ALTER TABLE "public"."token" ADD CONSTRAINT "token_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table token
-- ----------------------------
ALTER TABLE "public"."token" ADD CONSTRAINT "token_llm_model_fkey" FOREIGN KEY ("llm_model") REFERENCES "public"."llm" ("llm_model") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."token" ADD CONSTRAINT "token_username_fkey" FOREIGN KEY ("username") REFERENCES "public"."account" ("username") ON DELETE NO ACTION ON UPDATE NO ACTION;
